apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  accessModes:
    - "ReadWriteOnce" # ->
     # ReadOnlyMany   # ->
     # ReadWriteMany  # ->
  capacity:
    storage: 1Gi

  # hostPath
  awsElasticBlockStore:
    volumeID: <volume-ID>
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain #Delete #Recycle