apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ss
spec:
  serviceName: <service-name>
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-pod
        image: mysql
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /path
            name: <volume-name>
  # if not volumeClaimTemplate
      volumes:
        - name: <volume-name>
          persistentVolumeClaim:
            claimName: <pvc-name>

  
  # create pod -> provision PVC -> provision PV
  volumeClaimTemplates:
    - metadata:
        name: <volume-name>
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: google-storage 
        resources:
          requests:
            storage: 500Mi
