apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx-pod
          image: nginx
          imagePullPolicy: Always # or add [image:<image-name:latest>]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 10

