apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication
spec:
  replicas: 2
  selector:
    app: frontend 
  template:
    metadata:
      name: nginx-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
